import { CURRENT_CONGRESS, CURRENT_SESSION } from "@/lib/congress/constants";
import type { BillRecord, BillSponsorshipRecord, ImportRunRecord, SourceDocument, VotePositionRecord, VoteRecord } from "@/lib/congress/domain";
import { buildBillId } from "@/lib/congress/utils";

const sourceDocuments: SourceDocument[] = [
  {
    id: "seed-house-vote-2025-6",
    sourceSystem: "house-clerk",
    sourceType: "roll-call-vote",
    externalId: "20256",
    url: "https://clerk.house.gov/Votes/20256",
    retrievedAt: "2026-04-22T13:59:00Z",
    note: "Official House Clerk roll call vote page used for seeded House positions.",
  },
  {
    id: "seed-senate-vote-2026-11",
    sourceSystem: "senate",
    sourceType: "roll-call-vote",
    externalId: "vote_119_2_00011",
    url: "https://www.senate.gov/legislative/LIS/roll_call_votes/vote1192/vote_119_2_00011.xml",
    retrievedAt: "2026-04-22T13:59:00Z",
    note: "Official Senate roll call XML used for seeded Senate positions.",
  },
  {
    id: "seed-bill-hr3702",
    sourceSystem: "congress-gov",
    sourceType: "bill",
    externalId: "hr3702-119",
    url: "https://www.congress.gov/bill/119th-congress/house-bill/3702",
    retrievedAt: "2026-04-22T13:59:00Z",
  },
  {
    id: "seed-bill-hr6481",
    sourceSystem: "congress-gov",
    sourceType: "bill",
    externalId: "hr6481-119",
    url: "https://www.congress.gov/bill/119th-congress/house-bill/6481",
    retrievedAt: "2026-04-22T13:59:00Z",
  },
  {
    id: "seed-bill-s2495",
    sourceSystem: "congress-gov",
    sourceType: "bill",
    externalId: "s2495-119",
    url: "https://www.congress.gov/bill/119th-congress/senate-bill/2495",
    retrievedAt: "2026-04-22T13:59:00Z",
  },
  {
    id: "seed-bill-s2102",
    sourceSystem: "congress-gov",
    sourceType: "bill",
    externalId: "s2102-119",
    url: "https://www.congress.gov/bill/119th-congress/senate-bill/2102",
    retrievedAt: "2026-04-22T13:59:00Z",
  },
];

const bills: BillRecord[] = [
  {
    id: buildBillId("hr", 3702),
    slug: "hr-3702-extreme-heat-economic-study-act-of-2025",
    congressNumber: CURRENT_CONGRESS,
    billType: "hr",
    billNumber: 3702,
    originChamber: "house",
    officialTitle: "Extreme Heat Economic Study Act of 2025",
    shortTitle: "Extreme Heat Economic Study Act of 2025",
    introducedDate: "2025-06-04",
    latestActionText: "Referred to the House Committee on Energy and Commerce.",
    latestActionDate: "2025-06-04",
    statusLabel: "Introduced",
    congressUrl: "https://www.congress.gov/bill/119th-congress/house-bill/3702",
    sourceDocumentId: "seed-bill-hr3702",
  },
  {
    id: buildBillId("hr", 6481),
    slug: "hr-6481-federal-building-threat-notification-act",
    congressNumber: CURRENT_CONGRESS,
    billType: "hr",
    billNumber: 6481,
    originChamber: "house",
    officialTitle: "Federal Building Threat Notification Act",
    shortTitle: "Federal Building Threat Notification Act",
    introducedDate: "2025-12-04",
    latestActionText: "Ordered to be reported by voice vote.",
    latestActionDate: "2025-12-18",
    statusLabel: "Ordered Reported",
    congressUrl: "https://www.congress.gov/bill/119th-congress/house-bill/6481",
    sourceDocumentId: "seed-bill-hr6481",
  },
  {
    id: buildBillId("s", 2495),
    slug: "s-2495-keep-call-centers-in-america-act-of-2025",
    congressNumber: CURRENT_CONGRESS,
    billType: "s",
    billNumber: 2495,
    originChamber: "senate",
    officialTitle: "Keep Call Centers in America Act of 2025",
    shortTitle: "Keep Call Centers in America Act of 2025",
    introducedDate: "2025-07-29",
    latestActionText: "Read twice and referred to the Committee on Commerce, Science, and Transportation.",
    latestActionDate: "2025-07-29",
    statusLabel: "Introduced",
    congressUrl: "https://www.congress.gov/bill/119th-congress/senate-bill/2495",
    sourceDocumentId: "seed-bill-s2495",
  },
  {
    id: buildBillId("s", 2102),
    slug: "s-2102-ralph-david-abernathy-sr-national-historic-site-act",
    congressNumber: CURRENT_CONGRESS,
    billType: "s",
    billNumber: 2102,
    originChamber: "senate",
    officialTitle: "Ralph David Abernathy, Sr., National Historic Site Act",
    shortTitle: "Ralph David Abernathy, Sr., National Historic Site Act",
    introducedDate: "2025-06-17",
    latestActionText: "Read twice and referred to the Committee on Energy and Natural Resources.",
    latestActionDate: "2025-06-17",
    statusLabel: "Introduced",
    congressUrl: "https://www.congress.gov/bill/119th-congress/senate-bill/2102",
    sourceDocumentId: "seed-bill-s2102",
  },
];

const billSponsorships: BillSponsorshipRecord[] = [
  {
    id: "sponsor-hr3702-ansari",
    billId: buildBillId("hr", 3702),
    memberId: "member-house-a000381",
    sponsorshipType: "sponsor",
    isPrimary: true,
    sponsorshipDate: "2025-06-04",
    sourceDocumentId: "seed-bill-hr3702",
  },
  {
    id: "sponsor-hr6481-stanton",
    billId: buildBillId("hr", 6481),
    memberId: "member-house-s001211",
    sponsorshipType: "sponsor",
    isPrimary: true,
    sponsorshipDate: "2025-12-04",
    sourceDocumentId: "seed-bill-hr6481",
  },
  {
    id: "sponsor-s2495-gallego",
    billId: buildBillId("s", 2495),
    memberId: "member-senate-g000574",
    sponsorshipType: "sponsor",
    isPrimary: true,
    sponsorshipDate: "2025-07-29",
    sourceDocumentId: "seed-bill-s2495",
  },
  {
    id: "sponsor-s2102-ossoff",
    billId: buildBillId("s", 2102),
    memberId: "member-senate-o000174",
    sponsorshipType: "sponsor",
    isPrimary: true,
    sponsorshipDate: "2025-06-17",
    sourceDocumentId: "seed-bill-s2102",
  },
];

const votes: VoteRecord[] = [
  {
    id: "vote-house-119-1-6",
    slug: "house-119-1-6-hr-29-laken-riley-act",
    chamber: "house",
    congressNumber: CURRENT_CONGRESS,
    sessionNumber: 1,
    rollCallNumber: 6,
    voteDate: "2025-01-07",
    title: "H.R. 29",
    question: "On Passage",
    resultText: "Passed",
    voteType: "Yea-And-Nay",
    officialSourceUrl: "https://clerk.house.gov/Votes/20256",
    sourceDocumentId: "seed-house-vote-2025-6",
  },
  {
    id: "vote-senate-119-2-11",
    slug: "senate-119-2-11-hr-6938-appropriations",
    chamber: "senate",
    congressNumber: CURRENT_CONGRESS,
    sessionNumber: CURRENT_SESSION,
    rollCallNumber: 11,
    voteDate: "2026-01-15",
    title: "H.R. 6938",
    question: "On Passage of the Bill H.R. 6938",
    resultText: "Bill Passed (82-15)",
    voteType: "1/2",
    officialSourceUrl: "https://www.senate.gov/legislative/LIS/roll_call_votes/vote1192/vote_119_2_00011.xml",
    relatedBillId: buildBillId("hr", 6938),
    sourceDocumentId: "seed-senate-vote-2026-11",
  },
];

const votePositions: VotePositionRecord[] = [
  {
    id: "vote-house-6-ansari",
    voteId: "vote-house-119-1-6",
    memberId: "member-house-a000381",
    positionCode: "nay",
    positionLabel: "Nay",
    sourceDocumentId: "seed-house-vote-2025-6",
  },
  {
    id: "vote-house-6-stanton",
    voteId: "vote-house-119-1-6",
    memberId: "member-house-s001211",
    positionCode: "yea",
    positionLabel: "Yea",
    sourceDocumentId: "seed-house-vote-2025-6",
  },
  {
    id: "vote-house-6-fitzpatrick",
    voteId: "vote-house-119-1-6",
    memberId: "member-house-f000466",
    positionCode: "yea",
    positionLabel: "Yea",
    sourceDocumentId: "seed-house-vote-2025-6",
  },
  {
    id: "vote-house-6-dingell",
    voteId: "vote-house-119-1-6",
    memberId: "member-house-d000624",
    positionCode: "nay",
    positionLabel: "Nay",
    sourceDocumentId: "seed-house-vote-2025-6",
  },
  {
    id: "vote-house-6-mcbath",
    voteId: "vote-house-119-1-6",
    memberId: "member-house-m001208",
    positionCode: "yea",
    positionLabel: "Yea",
    sourceDocumentId: "seed-house-vote-2025-6",
  },
  {
    id: "vote-house-6-williams",
    voteId: "vote-house-119-1-6",
    memberId: "member-house-w000788",
    positionCode: "nay",
    positionLabel: "Nay",
    sourceDocumentId: "seed-house-vote-2025-6",
  },
  {
    id: "vote-senate-11-gallego",
    voteId: "vote-senate-119-2-11",
    memberId: "member-senate-g000574",
    positionCode: "yea",
    positionLabel: "Yea",
    sourceDocumentId: "seed-senate-vote-2026-11",
  },
  {
    id: "vote-senate-11-kelly",
    voteId: "vote-senate-119-2-11",
    memberId: "member-senate-k000377",
    positionCode: "yea",
    positionLabel: "Yea",
    sourceDocumentId: "seed-senate-vote-2026-11",
  },
  {
    id: "vote-senate-11-fetterman",
    voteId: "vote-senate-119-2-11",
    memberId: "member-senate-f000479",
    positionCode: "yea",
    positionLabel: "Yea",
    sourceDocumentId: "seed-senate-vote-2026-11",
  },
  {
    id: "vote-senate-11-mccormick",
    voteId: "vote-senate-119-2-11",
    memberId: "member-senate-m001243",
    positionCode: "yea",
    positionLabel: "Yea",
    sourceDocumentId: "seed-senate-vote-2026-11",
  },
  {
    id: "vote-senate-11-peters",
    voteId: "vote-senate-119-2-11",
    memberId: "member-senate-p000595",
    positionCode: "yea",
    positionLabel: "Yea",
    sourceDocumentId: "seed-senate-vote-2026-11",
  },
  {
    id: "vote-senate-11-slotkin",
    voteId: "vote-senate-119-2-11",
    memberId: "member-senate-s001208",
    positionCode: "yea",
    positionLabel: "Yea",
    sourceDocumentId: "seed-senate-vote-2026-11",
  },
  {
    id: "vote-senate-11-ossoff",
    voteId: "vote-senate-119-2-11",
    memberId: "member-senate-o000174",
    positionCode: "yea",
    positionLabel: "Yea",
    sourceDocumentId: "seed-senate-vote-2026-11",
  },
  {
    id: "vote-senate-11-warnock",
    voteId: "vote-senate-119-2-11",
    memberId: "member-senate-w000790",
    positionCode: "yea",
    positionLabel: "Yea",
    sourceDocumentId: "seed-senate-vote-2026-11",
  },
];

const importRuns: ImportRunRecord[] = [
  {
    id: "seed-import-house-votes",
    pipelineName: "seed-house-votes",
    status: "succeeded",
    startedAt: "2026-04-22T13:59:00Z",
    completedAt: "2026-04-22T13:59:00Z",
    recordsSeen: 1,
    recordsInserted: 1,
    recordsUpdated: 0,
    recordsFailed: 0,
  },
  {
    id: "seed-import-senate-votes",
    pipelineName: "seed-senate-votes",
    status: "succeeded",
    startedAt: "2026-04-22T13:59:00Z",
    completedAt: "2026-04-22T13:59:00Z",
    recordsSeen: 1,
    recordsInserted: 1,
    recordsUpdated: 0,
    recordsFailed: 0,
  },
];

export const seededLegislativeData = {
  sourceDocuments,
  bills,
  billSponsorships,
  votes,
  votePositions,
  importRuns,
};
